development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['JETTY_PORT'] || 8983 %>/fedora/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:<%= ENV['JETTY_PORT'] || 8983 %>/fedora/rest
  base_path: /test